# Generated by Django 4.2 on 2023-05-10 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20230509_0200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='creat_on',
            new_name='created_on',
        ),
    ]
